# Generated by Django 3.1.1 on 2020-10-13 08:47

from django.db import migrations


def fill_data_to_db(apps, schema_editor):
	'''
	We can't import the Post model directly as it may be a newer
	version than this migration expects. We use the historical version.
	'''
	Station = apps.get_model('music', 'Station')
	Author = apps.get_model('music', 'Author')
	Track = apps.get_model('music', 'Track')

	tracks = {
		"Rammstein": {
			"year": 1994,
			"station": "Metal",
			"songs": [
				"Sonne", 
				"Mutter"
			]
		},
		"Цой": {
			"year": 1981,
			"station": "Rock",
			"songs": [
				"Звезда", 
				"Пачка сигарет", 
				"Перемен", 
				"Стук"
			]
		},
		"Ария": {
			"year": 1985,
			"station": "Classical",
			"songs": [
				"Беспечный ангел", 
				"Штиль", "Я свободен", 
				"Темная башня"
			]
		},
		"Scorpions": {
			"year": 1965,
			"station": "Jazz",
			"songs": [
				"Still loving you", 
				"The wind of change"
			]
		},
		"The Mavericks": {
			"year": 1989,
			"station": "Rock",
			"songs": [
				"A Better Way", 
				"All Night Long", 
				"Back in Your Arms", 
				"All Over Again"
			]
		}

	}

	categories = ["Rock", "Pop", "Classical", "Jazz", "Bardic", "Punk", "Metal"]
	for category in categories:
		station = Station(name=category)
		station.save()

	for group in tracks.keys():
		author = Author(name=group, year=tracks[group]["year"])
		author.save()
		station = Station.objects.get(name=tracks[group]["station"])
		for song in tracks[group]["songs"]:
			track = Track(name=song, author=author)
			track.save()
			track.station.add(station)
			track.save()
	

class Migration(migrations.Migration):

	dependencies = [
		('music', '0001_initial'),
	]

	operations = [
		migrations.RunPython(fill_data_to_db),
	]
