version: '3.7'

services:
  web:
    build: ../shurik-music
    # entrypoint: "./entrypoint.sh"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../shurik-music/:/usr/src/shurik-music/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shurik
      - POSTGRES_PASSWORD=Lampard8
      - POSTGRES_DB=shurik_music
volumes:
  postgres_data: